import React, { Component } from 'react';

class Index extends Component {

    render() {
        return (
            <div>
                <h1>Home Page</h1>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut nemo dubitet, eorum omnia officia quo spectare, quid sequi, quid fugere debeant? Itaque ne iustitiam quidem recte quis dixerit per se ipsam optabilem, sed quia iucunditatis vel plurimum afferat. Nec vero audiendus Hieronymus, cui summum bonum est idem, quod vos interdum vel potius nimium saepe dicitis, nihil dolere. Summum ením bonum exposuit vacuitatem doloris; Duo Reges: constructio interrete. Atqui haec patefactio quasi rerum opertarum, cum quid quidque sit aperitur, definitio est. Utilitatis causa amicitia est quaesita. Magni enim aestimabat pecuniam non modo non contra leges, sed etiam legibus partam. Si enim Zenoni licuit, cum rem aliquam invenisset inusitatam, inauditum quoque ei rei nomen inponere, cur non liceat Catoni? Themistocles quidem, cum ei Simonides an quis alius artem memoriae polliceretur, Oblivionis, inquit, mallem. Itaque his sapiens semper vacabit. Itaque ne iustitiam quidem recte quis dixerit per se ipsam optabilem, sed quia iucunditatis vel plurimum afferat. Licet hic rursus ea commemores, quae optimis verbis ab Epicuro de laude amicitiae dicta sunt. Materiam vero rerum et copiam apud hos exilem, apud illos uberrimam reperiemus. </p>

                <p>A villa enim, credo, et: Si ibi te esse scissem, ad te ipse venissem. Dat enim id nobis solitudo, quod si qui deus diceret, numquam putarem me in Academia tamquam philosophum disputaturum. Tanti autem aderant vesicae et torminum morbi, ut nihil ad eorum magnitudinem posset accedere. Nunc haec primum fortasse audientis servire debemus. Equidem e Cn. At quanta conantur! Mundum hunc omnem oppidum esse nostrum! Incendi igitur eos, qui audiunt, vides. <i>At ille pellit, qui permulcet sensum voluptate.</i> Iam quae corporis sunt, ea nec auctoritatem cum animi partibus, comparandam et cognitionem habent faciliorem. <i>Si enim ad populum me vocas, eum.</i> <a href="http://loripsum.net/" target="_blank">Apparet statim, quae sint officia, quae actiones.</a> <a href="http://loripsum.net/" target="_blank">Prodest, inquit, mihi eo esse animo.</a> Tuo vero id quidem, inquam, arbitratu. Sed fac ista esse non inportuna; Illis videtur, qui illud non dubitant bonum dicere -; Qui enim voluptatem ipsam contemnunt, iis licet dicere se acupenserem maenae non anteponere. Si longus, levis; </p>

                <p>His similes sunt omnes, qui virtuti student levantur vitiis, levantur erroribus, nisi forte censes Ti. Sed ne, dum huic obsequor, vobis molestus sim. <b>Vestri haec verecundius, illi fortasse constantius.</b> <mark>An nisi populari fama?</mark> Quae qui non vident, nihil umquam magnum ac cognitione dignum amaverunt. Positum est a nostris in iis esse rebus, quae secundum naturam essent, non dolere; Ratio ista, quam defendis, praecepta, quae didicisti, quae probas, funditus evertunt amicitiam, quamvis eam Epicurus, ut facit, in caelum efferat laudibus. <mark>Honesta oratio, Socratica, Platonis etiam.</mark> </p>

                <p>Non enim solum Torquatus dixit quid sentiret, sed etiam cur. Praeterea et appetendi et refugiendi et omnino rerum gerendarum initia proficiscuntur aut a voluptate aut a dolore. <i>Huius ego nunc auctoritatem sequens idem faciam.</i> Immo istud quidem, inquam, quo loco quidque, nisi iniquum postulo, arbitratu meo. Dic in quovis conventu te omnia facere, ne doleas. Cur igitur, cum de re conveniat, non malumus usitate loqui? Hoc loco tenere se Triarius non potuit. Quos qui tollunt et nihil posse percipi dicunt, ii remotis sensibus ne id ipsum quidem expedire possunt, quod disserunt. </p>

                <p>Critolaus imitari voluit antiquos, et quidem est gravitate proximus, et redundat oratio, ac tamen is quidem in patriis institutis manet. Sed eum qui audiebant, quoad poterant, defendebant sententiam suam. Sin tantum modo ad indicia veteris memoriae cognoscenda, curiosorum. Quibus rebus vita consentiens virtutibusque respondens recta et honesta et constans et naturae congruens existimari potest. Quia, cum a Zenone, inquam, hoc magnifice tamquam ex oraculo editur: Virtus ad beate vivendum se ipsa contenta est, et Quare? <b>Quod equidem non reprehendo;</b> Sed id ne cogitari quidem potest quale sit, ut non repugnet ipsum sibi. <b>Hic ambiguo ludimur.</b> </p>

                <p>Ergo in hac ratione tota de maximis fere rebus Stoici illos secuti sunt, ut et deos esse et quattuor ex rebus omnia constare dicerent. Modo etiam paulum ad dexteram de via declinavi, ut ad Pericli sepulcrum accederem. Potius ergo illa dicantur: turpe esse, viri non esse debilitari dolore, frangi, succumbere. Ego autem tibi, Piso, assentior usu hoc venire, ut acrius aliquanto et attentius de claris viris locorum admonitu cogitemus. <a href="http://loripsum.net/" target="_blank">Duarum enim vitarum nobis erunt instituta capienda.</a> Graecum enim hunc versum nostis omnes-: Suavis laborum est praeteritorum memoria. Hic ego: Etsi facit hic quidem, inquam, Piso, ut vides, ea, quae praecipis, tamen mihi grata hortatio tua est. Quia nec honesto quic quam honestius nec turpi turpius. </p>

                <p><b>Qui convenit?</b> Illud mihi a te nimium festinanter dictum videtur, sapientis omnis esse semper beatos; Quo modo autem optimum, si bonum praeterea nullum est? <b>Verba tu fingas et ea dicas, quae non sentias?</b> Sed memento te, quae nos sentiamus, omnia probare, nisi quod verbis aliter utamur, mihi autem vestrorum nihil probari. <i>Quam si explicavisset, non tam haesitaret.</i> Sed nonne merninisti licere mihi ista probare, quae sunt a te dicta? Quis enim potest ea, quae probabilia videantur ei, non probare? </p>

                <p>Est enim perspicuum nullam artem ipsam in se versari, sed esse aliud artem ipsam, aliud quod propositum sit arti. Ita multo sanguine profuso in laetitia et in victoria est mortuus. Semovenda est igitur voluptas, non solum ut recta sequamini, sed etiam ut loqui deceat frugaliter. Torquatus, is qui consul cum Cn. Nec enim figura corporis nec ratio excellens ingenii humani significat ad unam hanc rem natum hominem, ut frueretur voluptatibus. Nec enim ignoras his istud honestum non summum modo, sed etiam, ut tu vis, solum bonum videri. Apud ceteros autem philosophos, qui quaesivit aliquid, tacet; Etenim nec iustitia nec amicitia esse omnino poterunt, nisi ipsae per se expetuntur. Qui igitur convenit ab alia voluptate dicere naturam proficisci, in alia summum bonum ponere? Quid de Platone aut de Democrito loquar? <a href="http://loripsum.net/" target="_blank">Nulla erit controversia.</a> Res tota, Torquate, non doctorum hominum, velle post mortem epulis celebrari memoriam sui nominis. Id enim volumus, id contendimus, ut officii fructus sit ipsum officium. Commoda autem et incommoda in eo genere sunt, quae praeposita et reiecta diximus; Sed cum ea, quae praeterierunt, acri animo et attento intuemur, tum fit ut aegritudo sequatur, si illa mala sint, laetitia, si bona. Itaque sensibus rationem adiunxit et ratione effecta sensus non reliquit. </p>

                <p>Semper enim ex eo, quod maximas partes continet latissimeque funditur, tota res appellatur. <a href="http://loripsum.net/" target="_blank">Omnia contraria, quos etiam insanos esse vultis.</a> <a href="http://loripsum.net/" target="_blank">Quare attende, quaeso.</a> <b>Nemo igitur esse beatus potest.</b> Parvi enim primo ortu sic iacent, tamquam omnino sine animo sint. Is ita vivebat, ut nulla tam exquisita posset inveniri voluptas, qua non abundaret. </p>

                <p>Est autem situm in nobis ut et adversa quasi perpetua oblivione obruamus et secunda iucunde ac suaviter meminerimus. Septem autem illi non suo, sed populorum suffragio omnium nominati sunt. Nam haec ipsa mihi erunt in promptu, quae modo audivi, nec ante aggrediar, quam te ab istis, quos dicis, instructum videro. Haec non erant eius, qui innumerabilis mundos infinitasque regiones, quarum nulla esset ora, nulla extremitas, mente peragravisset. <a href="http://loripsum.net/" target="_blank">Itaque hic ipse iam pridem est reiectus;</a> Consequentia exquirere, quoad sit id, quod volumus, effectum. In his igitur partibus duabus nihil erat, quod Zeno commutare gestiret. Quid igitur, inquit, eos responsuros putas? Hanc ergo intuens debet institutum illud quasi signum absolvere. Ut ad minora veniam, mathematici, poëtae, musici, medici denique ex hac tamquam omnium artificum officina profecti sunt. Quis animo aequo videt eum, quem inpure ac flagitiose putet vivere? </p>

                <p><i>Ita prorsus, inquam;</i> <b>Ut optime, secundum naturam affectum esse possit.</b> <a href="http://loripsum.net/" target="_blank">Tum Torquatus: Prorsus, inquit, assentior;</a> Videmusne ut pueri ne verberibus quidem a contemplandis rebus perquirendisque deterreantur? <b>Quid de Pythagora?</b> <i>Confecta res esset.</i> Unum nescio, quo modo possit, si luxuriosus sit, finitas cupiditates habere. <a href="http://loripsum.net/" target="_blank">Maximus dolor, inquit, brevis est.</a> Quid de Pythagora? Ergo id est convenienter naturae vivere, a natura discedere. Hoc loco discipulos quaerere videtur, ut, qui asoti esse velint, philosophi ante fiant. <a href="http://loripsum.net/" target="_blank">Non quam nostram quidem, inquit Pomponius iocans;</a> Atque adhuc ea dixi, causa cur Zenoni non fuisset, quam ob rem a superiorum auctoritate discederet. Fieri, inquam, Triari, nullo pacto potest, ut non dicas, quid non probes eius, a quo dissentias. </p>

                <p>Nam quibus rebus efficiuntur voluptates, eae non sunt in potestate sapientis. Aristoteles, Xenocrates, tota illa familia non dabit, quippe qui valitudinem, vires, divitias, gloriam, multa alia bona esse dicant, laudabilia non dicant. Atque haec coniunctio confusioque virtutum tamen a philosophis ratione quadam distinguitur. Atque haec contra Aristippum, qui eam voluptatem non modo summam, sed solam etiam ducit, quam omnes unam appellamus voluptatem. Sed est forma eius disciplinae, sicut fere ceterarum, triplex: una pars est naturae, disserendi altera, vivendi tertia. Nunc ita separantur, ut disiuncta sint, quo nihil potest esse perversius. Mihi quidem Homerus huius modi quiddam vidisse videatur in iis, quae de Sirenum cantibus finxerit. Satis est tibi in te, satis in legibus, satis in mediocribus amicitiis praesidii. </p>

                <p>Nos commodius agimus. <b>At iam decimum annum in spelunca iacet.</b> Ab hoc autem quaedam non melius quam veteres, quaedam omnino relicta. Quibus rebus vita consentiens virtutibusque respondens recta et honesta et constans et naturae congruens existimari potest. Totum genus hoc Zeno et qui ab eo sunt aut non potuerunt aut noluerunt, certe reliquerunt. <mark>Quae autem natura suae primae institutionis oblita est?</mark> Summum ením bonum exposuit vacuitatem doloris; Sed residamus, inquit, si placet. <b>At ille pellit, qui permulcet sensum voluptate.</b> Rem unam praeclarissimam omnium maximeque laudandam, penitus viderent, quonam gaudio complerentur, cum tantopere eius adumbrata opinione laetentur? </p>

                <p>Quam similitudinem videmus in bestiis, quae primo, in quo loco natae sunt, ex eo se non commoventi deinde suo quaeque appetitu movetur. Quod dicit Epicurus etiam de voluptate, quae minime sint voluptates, eas obscurari saepe et obrui. Sed ad haec, nisi molestum est, habeo quae velim. Quibus rebus vita consentiens virtutibusque respondens recta et honesta et constans et naturae congruens existimari potest. Verum enim diceret, idque Socratem, qui voluptatem nullo loco numerat, audio dicentem, cibi condimentum esse famem, potionis sitim. Nam, ut sint illa vendibiliora, haec uberiora certe sunt. Qualem igitur hominem natura inchoavit? Ergo hoc quidem apparet, nos ad agendum esse natos. Praetereo multos, in bis doctum hominem et suavem, Hieronymum, quem iam cur Peripateticum appellem nescio. </p>

                <p><b>Non laboro, inquit, de nomine.</b> Itaque dicunt nec dubitant: mihi sic usus est, tibi ut opus est facto, fac. <b>Itaque fecimus.</b> Hoc ille tuus non vult omnibusque ex rebus voluptatem quasi mercedem exigit. <a href="http://loripsum.net/" target="_blank">Eadem fortitudinis ratio reperietur.</a> Materiam vero rerum et copiam apud hos exilem, apud illos uberrimam reperiemus. At certe gravius. Cuius etiam illi hortuli propinqui non memoriam solum mihi afferunt, sed ipsum videntur in conspectu meo ponere. <b>Si id dicis, vicimus.</b> </p>

                <p>Quo modo autem optimum, si bonum praeterea nullum est? Quae si potest singula consolando levare, universa quo modo sustinebit? Vitae autem degendae ratio maxime quidem illis placuit quieta. Erillus autem ad scientiam omnia revocans unum quoddam bonum vidit, sed nec optimum nec quo vita gubernari possit. <a href="http://loripsum.net/" target="_blank">Quae hic rei publicae vulnera inponebat, eadem ille sanabat.</a> <b>Iam in altera philosophiae parte.</b> Nam quid possumus facere melius? Haec bene dicuntur, nec ego repugno, sed inter sese ipsa pugnant. <b>Quorum altera prosunt, nocent altera.</b> <a href="http://loripsum.net/" target="_blank">Bonum integritas corporis: misera debilitas.</a> </p>

                <p>Et hunc idem dico, inquieta sed ad virtutes et ad vitia nihil interesse. Non igitur de improbo, sed de callido improbo quaerimus, qualis Q. Sed quot homines, tot sententiae; Themistocles quidem, cum ei Simonides an quis alius artem memoriae polliceretur, Oblivionis, inquit, mallem. Honestum igitur id intellegimus, quod tale est, ut detracta omni utilitate sine ullis praemiis fructibusve per se ipsum possit iure laudari. <mark>Quis Aristidem non mortuum diligit?</mark> <a href="http://loripsum.net/" target="_blank">At hoc in eo M.</a> Is enim percontando atque interrogando elicere solebat eorum opiniones, quibuscum disserebat, ut ad ea, quae ii respondissent, si quid videretur, diceret. Serpere anguiculos, nare anaticulas, evolare merulas, cornibus uti videmus boves, nepas aculeis. Rem unam praeclarissimam omnium maximeque laudandam, penitus viderent, quonam gaudio complerentur, cum tantopere eius adumbrata opinione laetentur? Quid paulo ante, inquit, dixerim nonne meministi, cum omnis dolor detractus esset, variari, non augeri voluptatem? Me igitur ipsum ames oportet, non mea, si veri amici futuri sumus. <a href="http://loripsum.net/" target="_blank">Si longus, levis;</a> Nam Metrodorum non puto ipsum professum, sed, cum appellaretur ab Epicuro, repudiare tantum beneficium noluisse; </p>

                <p>Sed alii dolore moventur, alii cupiditate, iracundia etiam multi effetuntur et, cum in mala scientes inruunt, tum se optime sibi consulere arbitrantur. An eum discere ea mavis, quae cum plane perdidiceriti nihil sciat? In voluptate corporis-addam, si vis, animi, dum ea ipsa, ut vultis, sit e corpore-situm est vivere beate. Honesta oratio, Socratica, Platonis etiam. Hoc est vim afferre, Torquate, sensibus, extorquere ex animis cognitiones verborum, quibus inbuti sumus. Aut unde est hoc contritum vetustate proverbium: quicum in tenebris? Nam Metrodorum non puto ipsum professum, sed, cum appellaretur ab Epicuro, repudiare tantum beneficium noluisse; Atqui reperies, inquit, in hoc quidem pertinacem; Pisone in eo gymnasio, quod Ptolomaeum vocatur, unaque nobiscum Q. <i>Cur, nisi quod turpis oratio est?</i> </p>

                <p>Ergo adhuc, quantum equidem intellego, causa non videtur fuisse mutandi nominis. Memini vero, inquam; Tubulum fuisse, qua illum, cuius is condemnatus est rogatione, P. Ut Phidias potest a primo instituere signum idque perficere, potest ab alio inchoatum accipere et absolvere, huic est sapientia similis; Quibus rebus vita consentiens virtutibusque respondens recta et honesta et constans et naturae congruens existimari potest. <mark>Utram tandem linguam nescio?</mark> Quae quidem adhuc peregrinari Romae videbatur nec offerre sese nostris sermonibus, et ista maxime propter limatam quandam et rerum et verborum tenuitatem. Quod, inquit, quamquam voluptatibus quibusdam est saepe iucundius, tamen expetitur propter voluptatem. Universa enim illorum ratione cum tota vestra confligendum puto. <i>Nam ista vestra: Si gravis, brevis;</i> Quos quidem tibi studiose et diligenter tractandos magnopere censeo. Non igitur potestis voluptate omnia dirigentes aut tueri aut retinere virtutem. Sin laboramus, quis est, qui alienae modum statuat industriae? Quamquam ego non quaero, quid tibi a me probatum sit, sed huic Ciceroni nostro, quem discipulum cupio a te abducere. </p>

                <p>Sed haec ab Antiocho, familiari nostro, dicuntur multo melius et fortius, quam a Stasea dicebantur. An dolor longissimus quisque miserrimus, voluptatem non optabiliorem diuturnitas facit? Quae dici eadem de ceteris virtutibus possunt, quarum omnium fundamenta vos in voluptate tamquam in aqua ponitis. Sed utrum hortandus es nobis, Luci, inquit, an etiam tua sponte propensus es? Itaque ne iustitiam quidem recte quis dixerit per se ipsam optabilem, sed quia iucunditatis vel plurimum afferat. At vero illa perfecta atque plena eorum, qui cum de hominis summo bono quaererent, nullam in eo neque animi neque corporis partem vacuam tutela reliquerunt. Alia quaedam dicent, credo, magna antiquorum esse peccata, quae ille veri investigandi cupidus nullo modo ferre potuerit. Quid ergo aliud intellegetur nisi uti ne quae pars naturae neglegatur? Restat locus huic disputationi vel maxime necessarius de amicitia, quam, si voluptas summum sit bonum, affirmatis nullam omnino fore. Vitae autem degendae ratio maxime quidem illis placuit quieta. Quae in controversiam veniunt, de iis, si placet, disseramus. Quibus natura iure responderit non esse verum aliunde finem beate vivendi, a se principia rei gerendae peti; </p>

                <p>Quod autem meum munus dicis non equidem recuso, sed te adiungo socium. Atqui iste locus est, Piso, tibi etiam atque etiam confirmandus, inquam; Si verbum sequimur, primum longius verbum praepositum quam bonum. <b>Nihil ad rem! Ne sit sane;</b> Quae in controversiam veniunt, de iis, si placet, disseramus. Quis enim potest istis, quae te, ut ais, delectant, brevibus et acutis auditis de sententia decedere? Quid enim mihi potest esse optatius quam cum Catone, omnium virtutum auctore, de virtutibus disputare? Nihilo beatiorem esse Metellum quam Regulum. Qui si omnes veri erunt, ut Epicuri ratio docet, tum denique poterit aliquid cognosci et percipi. Hoc non est positum in nostra actione. Cum ageremus, inquit, vitae beatum et eundem supremum diem, scribebamus haec. </p>

                <p>Quibus natura iure responderit non esse verum aliunde finem beate vivendi, a se principia rei gerendae peti; Quid, si reviviscant Platonis illi et deinceps qui eorum auditores fuerunt, et tecum ita loquantur? Ita graviter et severe voluptatem secrevit a bono. De ingenio eius in his disputationibus, non de moribus quaeritur. Ergo id est convenienter naturae vivere, a natura discedere. Effluit igitur voluptas corporis et prima quaeque avolat saepiusque relinquit causam paenitendi quam recordandi. Nam e quibus locis quasi thesauris argumenta depromerentur, vestri ne suspicati quidem sunt, superiores autem artificio et via tradiderunt. Hoc enim constituto in philosophia constituta sunt omnia. <i>Maximus dolor, inquit, brevis est.</i> Itaque hoc frequenter dici solet a vobis, non intellegere nos, quam dicat Epicurus voluptatem. In eo autem voluptas omnium Latine loquentium more ponitur, cum percipitur ea, quae sensum aliquem moveat, iucunditas. </p>

                <p><i>Magna laus.</i> Facete M. Si est nihil nisi corpus, summa erunt illa: valitudo, vacuitas doloris, pulchritudo, cetera. Rapior illuc, revocat autem Antiochus, nec est praeterea, quem audiamus. An eum locum libenter invisit, ubi Demosthenes et Aeschines inter se decertare soliti sunt? Sed ad haec, nisi molestum est, habeo quae velim. Longum est enim ad omnia respondere, quae a te dicta sunt. Qualem igitur hominem natura inchoavit? Cum autem venissemus in Academiae non sine causa nobilitata spatia, solitudo erat ea, quam volueramus. Sin autem voluptatem putat adiungendam eam, quae sit in motu-sic enim appellat hanc dulcem: in motu, illam nihil dolentis in stabilitate-, quid tendit? </p>

                <p>Ut placet, inquit, etsi enim illud erat aptius, aequum cuique concedere. Neque solum ea communia, verum etiam paria esse dixerunt. Quae tamen a te agetur non melior, quam illae sunt, quas interdum optines. <a href="http://loripsum.net/" target="_blank">Quo modo?</a> Reliqui sibi constiterunt, ut extrema cum initiis convenirent, ut Aristippo voluptas, Hieronymo doloris vacuitas, Carneadi frui principiis naturalibus esset extremum. <a href="http://loripsum.net/" target="_blank">Addidisti ad extremum etiam indoctum fuisse.</a> Haec dicuntur inconstantissime. Sunt etiam turpitudines plurimae, quae, nisi honestas natura plurimum valeat, cur non cadant in sapientem non est facile defendere. Illis videtur, qui illud non dubitant bonum dicere -; -, sed ut hoc iudicaremus, non esse in iis partem maximam positam beate aut secus vivendi. Itaque ne iustitiam quidem recte quis dixerit per se ipsam optabilem, sed quia iucunditatis vel plurimum afferat. Voluptatem cum summum bonum diceret, primum in eo ipso parum vidit, deinde hoc quoque alienum; In contemplatione et cognitione posita rerum, quae quia deorum erat vitae simillima, sapiente visa est dignissima. Chrysippus autem exponens differentias animantium ait alias earum corpore excellere, alias autem animo, non nullas valere utraque re; </p>

                <p>Quia, cum a Zenone, inquam, hoc magnifice tamquam ex oraculo editur: Virtus ad beate vivendum se ipsa contenta est, et Quare? Superiores tres erant, quae esse possent, quarum est una sola defensa, eaque vehementer. Sed et illum, quem nominavi, et ceteros sophistas, ut e Platone intellegi potest, lusos videmus a Socrate. Quam illa ardentis amores excitaret sui! Cur tandem? Quamquam haec quidem praeposita recte et reiecta dicere licebit. Cur tantas regiones barbarorum pedibus obiit, tot maria transmisit? Sed quid minus probandum quam esse aliquem beatum nec satis beatum? Atqui haec patefactio quasi rerum opertarum, cum quid quidque sit aperitur, definitio est. </p>

                <p><a href="http://loripsum.net/" target="_blank">Quam si explicavisset, non tam haesitaret.</a> Ita enim se Athenis collocavit, ut sit paene unus ex Atticis, ut id etiam cognomen videatur habiturus. <a href="http://loripsum.net/" target="_blank">Sed ad bona praeterita redeamus.</a> Dici enim nihil potest verius. Atque omnia quidem scire, cuiuscumque modi sint, cupere curiosorum, duci vero maiorum rerum contemplatione ad cupiditatem scientiae summorum virorum est putandum. Possumusne ergo in vita summum bonum dicere, cum id ne in cena quidem posse videamur? Nummus in Croesi divitiis obscuratur, pars est tamen divitiarum. Quare si potest esse beatus is, qui est in asperis reiciendisque rebus, potest is quoque esse. </p>

                <p><a href="http://loripsum.net/" target="_blank">Negare non possum.</a> Quare, quoniam de primis naturae commodis satis dietum est nunc de maioribus consequentibusque videamus. Sic vester sapiens magno aliquo emolumento commotus cicuta, si opus erit, dimicabit. <a href="http://loripsum.net/" target="_blank">Ostendit pedes et pectus.</a> Atqui haec patefactio quasi rerum opertarum, cum quid quidque sit aperitur, definitio est. Itaque primos congressus copulationesque et consuetudinum instituendarum voluntates fieri propter voluptatem; <a href="http://loripsum.net/" target="_blank">An eiusdem modi?</a> Tum ille: Tu autem cum ipse tantum librorum habeas, quos hic tandem requiris? </p>

                <p>Quae cum dixisset paulumque institisset, Quid est? Non enim, si omnia non sequebatur, idcirco non erat ortus illinc. Sed in rebus apertissimis nimium longi sumus. <i>Quae quidem vel cum periculo est quaerenda vobis;</i> <i>Ut id aliis narrare gestiant?</i> Experiamur igitur, inquit, etsi habet haec Stoicorum ratio difficilius quiddam et obscurius. Hic quoque suus est de summoque bono dissentiens dici vere Peripateticus non potest. </p>

                <p>Itaque nostrum est-quod nostrum dico, artis est-ad ea principia, quae accepimus. <a href="http://loripsum.net/" target="_blank">Si longus, levis;</a> Sed non alienum est, quo facilius vis verbi intellegatur, rationem huius verbi faciendi Zenonis exponere. <a href="http://loripsum.net/" target="_blank">Memini vero, inquam;</a> Cognitio autem haec est una nostri, ut vim corporis animique norimus sequamurque eam vitam, quae rebus iis ipsis perfruatur. Sin laboramus, quis est, qui alienae modum statuat industriae? An dolor longissimus quisque miserrimus, voluptatem non optabiliorem diuturnitas facit? Eiuro, inquit adridens, iniquum, hac quidem de re; In eo enim positum est id, quod dicimus esse expetendum. <i>Quid de Platone aut de Democrito loquar?</i> Tum Piso: Atqui, Cicero, inquit, ista studia, si ad imitandos summos viros spectant, ingeniosorum sunt; </p>

                <p>Multa sunt dicta ab antiquis de contemnendis ac despiciendis rebus humanis; Si quicquam extra virtutem habeatur in bonis. Si ista mala sunt, in quae potest incidere sapiens, sapientem esse non esse ad beate vivendum satis. Quin etiam ferae, inquit Pacuvius, quíbus abest, ad praécavendum intéllegendi astútia, iniecto terrore mortis horrescunt. Bonum appello quicquid secundurn naturam est, quod contra malum, nec ego solus, sed tu etiam, Chrysippe, in foro, domi; Qui autem voluptate vitam effici beatam putabit, qui sibi is conveniet, si negabit voluptatem crescere longinquitate? <mark>Non potes, nisi retexueris illa.</mark> Dic in quovis conventu te omnia facere, ne doleas. <mark>Sic enim censent, oportunitatis esse beate vivere.</mark> Ex quo illud efficitur, qui bene cenent omnis libenter cenare, qui libenter, non continuo bene. <b>Quae diligentissime contra Aristonem dicuntur a Chryippo.</b> </p>

                <p>Quae quidem sapientes sequuntur duce natura tamquam videntes; In voluptate corporis-addam, si vis, animi, dum ea ipsa, ut vultis, sit e corpore-situm est vivere beate. Quid est, quod ab ea absolvi et perfici debeat? <mark>Ita relinquet duas, de quibus etiam atque etiam consideret.</mark> Ex quo intellegitur nec intemperantiam propter se esse fugiendam temperantiamque expetendam, non quia voluptates fugiat, sed quia maiores consequatur. Hoc loco discipulos quaerere videtur, ut, qui asoti esse velint, philosophi ante fiant. Sin kakan malitiam dixisses, ad aliud nos unum certum vitium consuetudo Latina traduceret. Incommoda autem et commoda-ita enim estmata et dustmata appello-communia esse voluerunt, paria noluerunt. Portenta haec esse dicit, neque ea ratione ullo modo posse vivi; </p>

                <p><a href="http://loripsum.net/" target="_blank">Certe non potest.</a> Est autem a te semper dictum nec gaudere quemquam nisi propter corpus nec dolere. Ista ipsa, quae tu breviter: regem, dictatorem, divitem solum esse sapientem, a te quidem apte ac rotunde; Tubulum fuisse, qua illum, cuius is condemnatus est rogatione, P. Nec vero sum nescius esse utilitatem in historia, non modo voluptatem. </p>

                <p>At quicum ioca seria, ut dicitur, quicum arcana, quicum occulta omnia? <a href="http://loripsum.net/" target="_blank">Huius, Lyco, oratione locuples, rebus ipsis ielunior.</a> Mihi enim satis est, ipsis non satis. Ne tum quidem te respicies et cogitabis sibi quemque natum esse et suis voluptatibus? Hinc ceteri particulas arripere conati suam quisque videro voluit afferre sententiam. <i>Quis non odit sordidos, vanos, leves, futtiles?</i> </p>

                <p>In contemplatione et cognitione posita rerum, quae quia deorum erat vitae simillima, sapiente visa est dignissima. Aufidio, praetorio, erudito homine, oculis capto, saepe audiebam, cum se lucis magis quam utilitatis desiderio moveri diceret. Qui igitur convenit ab alia voluptate dicere naturam proficisci, in alia summum bonum ponere? Semovenda est igitur voluptas, non solum ut recta sequamini, sed etiam ut loqui deceat frugaliter. Nunc dicam de voluptate, nihil scilicet novi, ea tamen, quae te ipsum probaturum esse confidam. Non pugnem cum homine, cur tantum habeat in natura boni; Quam quidem certationem homo et acutus et diligens, Chrysippus, non contemnit totumque discrimen summi boni in earum comparatione positum putat. Tamen aberramus a proposito, et, ne longius, prorsus, inquam, Piso, si ista mala sunt, placet. <i>Num quid tale Democritus?</i> Collige omnia, quae soletis: Praesidium amicorum. Quid autem habent admirationis, cum prope accesseris? Non elogia monimentorum id significant, velut hoc ad portam: Hunc unum plurimae consentiunt gentes populi primarium fuisse virum. </p>

                <p>Rem unam praeclarissimam omnium maximeque laudandam, penitus viderent, quonam gaudio complerentur, cum tantopere eius adumbrata opinione laetentur? Atque adhuc ea dixi, causa cur Zenoni non fuisset, quam ob rem a superiorum auctoritate discederet. Animi enim quoque dolores percipiet omnibus partibus maiores quam corporis. <a href="http://loripsum.net/" target="_blank">Sed quid sentiat, non videtis.</a> Sed dum efficere vultis beatum sapientem, cum maximas animo voluptates percipiat omnibusque partibus maiores quam corpore, quid occurrat non videtis. Huic verbo omnes, qui ubique sunt, qui Latine sciunt, duas res subiciunt, laetitiam in animo, commotionem suavem iucunditatis in corpore. <a href="http://loripsum.net/" target="_blank">In schola desinis.</a> <a href="http://loripsum.net/" target="_blank">At, si voluptas esset bonum, desideraret.</a> <a href="http://loripsum.net/" target="_blank">Quae ista amicitia est?</a> Te enim iudicem aequum puto, modo quae dicat ille bene noris. Nam illud vehementer repugnat, eundem beatum esse et multis malis oppressum. </p>

                <p><a href="http://loripsum.net/" target="_blank">Nihil illinc huc pervenit.</a> Perturbationes autem nulla naturae vi commoventur, omniaque ea sunt opiniones ac iudicia levitatis. Itaque hic ipse iam pridem est reiectus; Si longus, levis; Sin dicit obscurari quaedam nec apparere, quia valde parva sint, nos quoque concedimus; Hoc unum Aristo tenuit: praeter vitia atque virtutes negavit rem esse ullam aut fugiendam aut expetendam. Nec vero pietas adversus deos nec quanta iis gratia debeatur sine explicatione naturae intellegi potest. Neque enim civitas in seditione beata esse potest nec in discordia dominorum domus; <b>Quacumque enim ingredimur, in aliqua historia vestigium ponimus.</b> Ita fit illa conclusio non solum vera, sed ita perspicua, ut dialectici ne rationem quidem reddi putent oportere: si illud, hoc; Prodest, inquit, mihi eo esse animo. </p>

                <p><a href="http://loripsum.net/" target="_blank">Equidem etiam Epicurum, in physicis quidem, Democriteum puto.</a> <b>Quorum altera prosunt, nocent altera.</b> Quod si ita se habeat, non possit beatam praestare vitam sapientia. <a href="http://loripsum.net/" target="_blank">Quid turpius quam sapientis vitam ex insipientium sermone pendere?</a> <i>Certe non potest.</i> <a href="http://loripsum.net/" target="_blank">Sit enim idem caecus, debilis.</a> Idem etiam dolorem saepe perpetiuntur, ne, si id non faciant, incidant in maiorem. An dubium est, quin virtus ita maximam partem optineat in rebus humanis, ut reliquas obruat? <i>Bonum valitudo: miser morbus.</i> <b>Non semper, inquam;</b> Stoici restant, ei quidem non unam aliquam aut alteram rem a nobis, sed totam ad se nostram philosophiam transtulerunt; </p>

                <p>Tu autem inter haec tantam multitudinem hominum interiectam non vides nec laetantium nec dolentium? Nihil enim arbitror esse magna laude dignum, quod te praetermissurum credam aut mortis aut doloris metu. Videamus animi partes, quarum est conspectus illustrior; Quae enim dici Latine posse non arbitrabar, ea dicta sunt a te verbis aptis nec minus plane quam dicuntur a Graecis. Ego autem existimo, si honestum esse aliquid ostendero, quod sit ipsum vi sua propter seque expetendum, iacere vestra omnia. <a href="http://loripsum.net/" target="_blank">Sed ea mala virtuti magnitudine obruebantur.</a> Atque ita re simpliciter primo collocata reliqua subtilius persequentes corporis bona facilem quandam rationem habere censebant; <i>Vide, quantum, inquam, fallare, Torquate.</i> Quae enim adhuc protulisti, popularia sunt, ego autem a te elegantiora desidero. Nam illud vehementer repugnat, eundem beatum esse et multis malis oppressum. <b>Cur, nisi quod turpis oratio est?</b> </p>

                <p>Age, inquies, ista parva sunt. Nam prius a se poterit quisque discedere quam appetitum earum rerum, quae sibi conducant, amittere. Et quidem, inquit, vehementer errat; <a href="http://loripsum.net/" target="_blank">Minime vero, inquit ille, consentit.</a> <a href="http://loripsum.net/" target="_blank">Sed videbimus.</a> Tanti autem aderant vesicae et torminum morbi, ut nihil ad eorum magnitudinem posset accedere. Nec tamen ille erat sapiens quis enim hoc aut quando aut ubi aut unde? Stoici autem, quod finem bonorum in una virtute ponunt, similes sunt illorum; <a href="http://loripsum.net/" target="_blank">Aliter enim nosmet ipsos nosse non possumus.</a> Tum ego: Non mehercule, inquam, soleo temere contra Stoicos, non quo illis admodum assentiar, sed pudore impedior; Utrum igitur tibi non placet, inquit, virtutisne tantam esse vim, ut ad beate vivendum se ipsa contenta sit? Ex quo intellegitur officium medium quiddam esse, quod neque in bonis ponatur neque in contrariis. </p>

                <p>Haec dicuntur fortasse ieiunius; <a href="http://loripsum.net/" target="_blank">Primum quid tu dicis breve?</a> Sed tu istuc dixti bene Latine, parum plane. Quo studio Aristophanem putamus aetatem in litteris duxisse? Est enim effectrix multarum et magnarum voluptatum. Dulce amarum, leve asperum, prope longe, stare movere, quadratum rotundum. Si alia sentit, inquam, alia loquitur, numquam intellegam quid sentiat; Cur fortior sit, si illud, quod tute concedis, asperum et vix ferendum putabit? Itaque primos congressus copulationesque et consuetudinum instituendarum voluntates fieri propter voluptatem; <i>Primum in nostrane potestate est, quid meminerimus?</i> <i>Si id dicis, vicimus.</i> Aliud est enim poëtarum more verba fundere, aliud ea, quae dicas, ratione et arte distinguere. </p>

                <p><b>Sint modo partes vitae beatae.</b> <b>Quo tandem modo?</b> Itaque eos id agere, ut a se dolores, morbos, debilitates repellant. <a href="http://loripsum.net/" target="_blank">Aperiendum est igitur, quid sit voluptas;</a> Nemo enim est, qui aliter dixerit quin omnium naturarum simile esset id, ad quod omnia referrentur, quod est ultimum rerum appetendarum. <i>Cyrenaici quidem non recusant;</i> Hoc est vim afferre, Torquate, sensibus, extorquere ex animis cognitiones verborum, quibus inbuti sumus. Nec tamen ullo modo summum pecudis bonum et hominis idem mihi videri potest. <b>Immo alio genere;</b> Quid enim mihi potest esse optatius quam cum Catone, omnium virtutum auctore, de virtutibus disputare? Nunc ita separantur, ut disiuncta sint, quo nihil potest esse perversius. </p>

                <p>Cur iustitia laudatur? An est aliquid per se ipsum flagitiosum, etiamsi nulla comitetur infamia? Scis enim me quodam tempore Metapontum venisse tecum neque ad hospitem ante devertisse, quam Pythagorae ipsum illum locum, ubi vitam ediderat, sedemque viderim. Sunt autem, qui dicant foedus esse quoddam sapientium, ut ne minus amicos quam se ipsos diligant. Quare istam quoque aggredere tractatam praesertim et ab aliis et a te ipso saepe, ut tibi deesse non possit oratio. <b>Sed haec quidem liberius ab eo dicuntur et saepius.</b> Deinde prima illa, quae in congressu solemus: Quid tu, inquit, huc? <a href="http://loripsum.net/" target="_blank">Aliud igitur esse censet gaudere, aliud non dolere.</a> <i>Neutrum vero, inquit ille.</i> Sed ad haec, nisi molestum est, habeo quae velim. Omnes, qui non sint sapientes, aeque miseros esse, sapientes omnes summe beatos, recte facta omnia aequalia, omnia peccata paria; <mark>Sed tamen intellego quid velit.</mark> </p>

                <p>Cuius etiam illi hortuli propinqui non memoriam solum mihi afferunt, sed ipsum videntur in conspectu meo ponere. Hoc non est positum in nostra actione. Innumerabilia dici possunt in hanc sententiam, sed non necesse est. Cenasti in vita numquam bene, cum omnia in ista Consumis squilla atque acupensere cum decimano. Simul atque natum animal est, gaudet voluptate et eam appetit ut bonum, aspernatur dolorem ut malum. Quid igitur dubitamus in tota eius natura quaerere quid sit effectum? Quasi vero aut concedatur in omnibus stultis aeque magna esse vitia, et eadem inbecillitate et inconstantia L. Quasi vero aut concedatur in omnibus stultis aeque magna esse vitia, et eadem inbecillitate et inconstantia L. Persecutus est Aristoteles animantium omnium ortus, victus, figuras, Theophrastus autem stirpium naturas omniumque fere rerum, quae e terra gignerentur, causas atque rationes; Is enim percontando atque interrogando elicere solebat eorum opiniones, quibuscum disserebat, ut ad ea, quae ii respondissent, si quid videretur, diceret. </p>

                <p>Quod cum ita sit, perspicuum est omnis rectas res atque laudabilis eo referri, ut cum voluptate vivatur. Cuius quidem, quoniam Stoicus fuit, sententia condemnata mihi videtur esse inanitas ista verborum. Quid ergo hoc loco intellegit honestum? Aufidio, praetorio, erudito homine, oculis capto, saepe audiebam, cum se lucis magis quam utilitatis desiderio moveri diceret. Res enim fortasse verae, certe graves, non ita tractantur, ut debent, sed aliquanto minutius. <mark>Quod ea non occurrentia fingunt, vincunt Aristonem;</mark> </p>

                <p>Color egregius, integra valitudo, summa gratia, vita denique conferta voluptatum omnium varietate. Nam e quibus locis quasi thesauris argumenta depromerentur, vestri ne suspicati quidem sunt, superiores autem artificio et via tradiderunt. In qua si nihil est praeter rationem, sit in una virtute finis bonorum; Praeclare Laelius, et recte sofñw, illudque vere: O Publi, o gurges, Galloni! es homo miser, inquit. <a href="http://loripsum.net/" target="_blank">Ostendit pedes et pectus.</a> Quare hoc videndum est, possitne nobis hoc ratio philosophorum dare. </p>

                <p>Atque haec ita iustitiae propria sunt, ut sint virtutum reliquarum communia. Itaque e contrario moderati aequabilesque habitus, affectiones ususque corporis apti esse ad naturam videntur. Fortitudinis quaedam praecepta sunt ac paene leges, quae effeminari virum vetant in dolore. Si alia sentit, inquam, alia loquitur, numquam intellegam quid sentiat; Quod enim vituperabile est per se ipsum, id eo ipso vitium nominatum puto, vel etiam a vitio dictum vituperari. <mark>Quo modo autem philosophus loquitur?</mark> <mark>Huius, Lyco, oratione locuples, rebus ipsis ielunior.</mark> Res enim fortasse verae, certe graves, non ita tractantur, ut debent, sed aliquanto minutius. Quoniamque non dubium est quin in iis, quae media dicimus, sit aliud sumendum, aliud reiciendum, quicquid ita fit aut dicitur, omne officio continetur. Tenesne igitur, inquam, Hieronymus Rhodius quid dicat esse summum bonum, quo putet omnia referri oportere? </p>

                <p>Quam tu ponis in verbis, ego positam in re putabam. Illud urgueam, non intellegere eum quid sibi dicendum sit, cum dolorem summum malum esse dixerit. De ingenio eius in his disputationibus, non de moribus quaeritur. Est tamen ea secundum naturam multoque nos ad se expetendam magis hortatur quam superiora omnia. Nec enim, cum tua causa cui commodes, beneficium illud habendum est, sed faeneratio, nec gratia deberi videtur ei, qui sua causa commodaverit. <a href="http://loripsum.net/" target="_blank">Pauca mutat vel plura sane;</a> </p>

                <p>Quod autem meum munus dicis non equidem recuso, sed te adiungo socium. <mark>Haec quo modo conveniant, non sane intellego.</mark> Hic ego: Pomponius quidem, inquam, noster iocari videtur, et fortasse suo iure. Quem ad modum quis ambulet, sedeat, qui ductus oris, qui vultus in quoque sit? <a href="http://loripsum.net/" target="_blank">Quare attende, quaeso.</a> <i>Idemne, quod iucunde?</i> Duae sunt enim res quoque, ne tu verba solum putes. Cum autem negant ea quicquam ad beatam vitam pertinere, rursus naturam relinquunt. Sed existimo te, sicut nostrum Triarium, minus ab eo delectari, quod ista Platonis, Aristoteli, Theophrasti orationis ornamenta neglexerit. </p>

                <p>Cum autem progrediens confirmatur animus, agnoscit ille quidem naturae vim, sed ita, ut progredi possit longius, per se sit tantum inchoata. <i>Sed hoc sane concedamus.</i> Id autem eius modi est, ut additum ad virtutem auctoritatem videatur habiturum et expleturum cumulate vitam beatam, de quo omnis haec quaestio est. Ergo hoc quidem apparet, nos ad agendum esse natos. Non est enim vitium in oratione solum, sed etiam in moribus. Quid interest, nisi quod ego res notas notis verbis appello, illi nomina nova quaerunt, quibus idem dicant? Animadverti, ínquam, te isto modo paulo ante ponere, et scio ab Antiocho nostro dici sic solere; <b>Ita prorsus, inquam;</b> <a href="http://loripsum.net/" target="_blank">Magna laus.</a> Poterat autem inpune; Quod non faceret, si in voluptate summum bonum poneret. </p>

                <p><mark>ALIO MODO.</mark> Ego quoque, inquit, didicerim libentius si quid attuleris, quam te reprehenderim. An hoc usque quaque, aliter in vita? Ut etiam contendant et elaborent, si efficere possint, ut aut non appareat corporis vitium aut quam minimum appareat? Teneo, inquit, finem illi videri nihil dolere. Nec lapathi suavitatem acupenseri Galloni Laelius anteponebat, sed suavitatem ipsam neglegebat; <i>Quod ea non occurrentia fingunt, vincunt Aristonem;</i> </p>

                <p><mark>Quid enim est a Chrysippo praetermissum in Stoicis?</mark> Praeclare Laelius, et recte sofñw, illudque vere: O Publi, o gurges, Galloni! es homo miser, inquit. Ego autem tibi, Piso, assentior usu hoc venire, ut acrius aliquanto et attentius de claris viris locorum admonitu cogitemus. <mark>Hic nihil fuit, quod quaereremus.</mark> </p>

                <p>Inquit, an parum disserui non verbis Stoicos a Peripateticis, sed universa re et tota sententia dissidere? Iam quae corporis sunt, ea nec auctoritatem cum animi partibus, comparandam et cognitionem habent faciliorem. Itaque e contrario moderati aequabilesque habitus, affectiones ususque corporis apti esse ad naturam videntur. Quid ergo aliud intellegetur nisi uti ne quae pars naturae neglegatur? Qui enim existimabit posse se miserum esse beatus non erit. Dici enim nihil potest verius. Quaeque de virtutibus dicta sunt, quem ad modum eae semper voluptatibus inhaererent, eadem de amicitia dicenda sunt. Ab hoc autem quaedam non melius quam veteres, quaedam omnino relicta. At negat Epicurus-hoc enim vestrum lumen estquemquam, qui honeste non vivat, iucunde posse vivere. Ut ad minora veniam, mathematici, poëtae, musici, medici denique ex hac tamquam omnium artificum officina profecti sunt. </p>

                <p><b>Cum audissem Antiochum, Brute, ut solebam, cum M.</b> Sed id ne cogitari quidem potest quale sit, ut non repugnet ipsum sibi. Quem si tenueris, non modo meum Ciceronem, sed etiam me ipsum abducas licebit. Primum non saepe, deinde quae est ista relaxatio, cum et praeteriti doloris memoria recens est et futuri atque inpendentis torquet timor? Res enim se praeclare habebat, et quidem in utraque parte. <b>Deprehensus omnem poenam contemnet.</b> Nam e quibus locis quasi thesauris argumenta depromerentur, vestri ne suspicati quidem sunt, superiores autem artificio et via tradiderunt. Expectoque quid ad id, quod quaerebam, respondeas. Nam ante Aristippus, et ille melius. Nunc omni virtuti vitium contrario nomine opponitur. <b>Sullae consulatum?</b> </p>

                <p>Illa enim, quae prosunt aut quae nocent, aut bona sunt aut mala, quae sint paria necesse est. Illud urgueam, non intellegere eum quid sibi dicendum sit, cum dolorem summum malum esse dixerit. Aliter enim nosmet ipsos nosse non possumus. Istam voluptatem perpetuam quis potest praestare sapienti? <i>Non est igitur summum malum dolor.</i> Et quidem, inquit, vehementer errat; <a href="http://loripsum.net/" target="_blank">Quis est tam dissimile homini.</a> <b>Ad eos igitur converte te, quaeso.</b> Reperiam multos, vel innumerabilis potius, non tam curiosos nec tam molestos, quam vos estis, quibus, quid velim, facile persuadeam. Quare, quoniam de primis naturae commodis satis dietum est nunc de maioribus consequentibusque videamus. Nam illud quidem adduci vix possum, ut ea, quae senserit ille, tibi non vera videantur. Inquit, cum ego te hac nova lege videam eodem die accusatori responderet tribus horis perorare, in hac me causa tempus dilaturum putas? <b>Restinguet citius, si ardentem acceperit.</b> </p>

                <p><mark>Cur id non ita fit?</mark> Audax negotium, dicerem impudens, nisi hoc institutum postea translatum ad philosophos nostros esset. <b>Quae est igitur causa istarum angustiarum?</b> <mark>Tamen a proposito, inquam, aberramus.</mark> Conferam tecum, quam cuique verso rem subicias; Non quaero, quid dicat, sed quid convenienter possit rationi et sententiae suae dicere. Ex quo illud efficitur, qui bene cenent omnis libenter cenare, qui libenter, non continuo bene. </p>

                <p><a href="http://loripsum.net/" target="_blank">Sullae consulatum?</a> Quae rursus dum sibi evelli ex ordine nolunt, horridiores evadunt, asperiores, duriores et oratione et moribus. Hic, qui utrumque probat, ambobus debuit uti, sicut facit re, neque tamen dividit verbis. Ut ei, qui iucunde vixerit annos decem, si aeque vita iucunda menstrua addatur, quia momentum aliquod habeat ad iucundum accessio, bonum sit; <a href="http://loripsum.net/" target="_blank">Utilitatis causa amicitia est quaesita.</a> Quam tu ponis in verbis, ego positam in re putabam. Num igitur dubium est, quin, si in re ipsa nihil peccatur a superioribus, verbis illi commodius utantur? <i>Easdemne res?</i> In enumerandis autem corporis commodis si quis praetermissam a nobis voluptatem putabit, in aliud tempus ea quaestio differatur. Nos autem non solum beatae vitae istam esse oblectationem videmus, sed etiam levamentum miseriarum. Maximas vero virtutes iacere omnis necesse est voluptate dominante. Quae enim constituta sunt prima naturae, ad ea si voluptas accesserit, unum aliquod accesserit commodum corporis neque eam constitutionem summi boni, quae est proposta, mutaverit. Non minor, inquit, voluptas percipitur ex vilissimis rebus quam ex pretiosissimis. <b>Inde igitur, inquit, ordiendum est.</b> <a href="http://loripsum.net/" target="_blank">Quippe: habes enim a rhetoribus;</a> Aliam vero vim voluptatis esse, aliam nihil dolendi, nisi valde pertinax fueris, concedas necesse est. </p>

                <p>Qui cum praetor quaestionem inter sicarios exercuisset, ita aperte cepit pecunias ob rem iudicandam, ut anno proximo P. <a href="http://loripsum.net/" target="_blank">Cum praesertim illa perdiscere ludus esset.</a> Illa sunt similia: hebes acies est cuipiam oculorum, corpore alius senescit; Qui non moveatur et offensione turpitudinis et comprobatione honestatis? Qui si ea, quae dicit, ita sentiret, ut verba significant, quid inter eum et vel Pyrrhonem vel Aristonem interesset? <a href="http://loripsum.net/" target="_blank">Eademne, quae restincta siti?</a> </p>

                <p>Tu autem negas fortem esse quemquam posse, qui dolorem malum putet. Sed erat aequius Triarium aliquid de dissensione nostra iudicare. Ex quo intellegitur idem illud, solum bonum esse, quod honestum sit, idque esse beate vivere: honeste, id est cum virtute, vivere. Sextilio Rufo, cum is rem ad amicos ita deferret, se esse heredem Q. Egone non intellego, quid sit don Graece, Latine voluptas? </p>

                <p>Quid ei reliquisti, nisi te, quoquo modo loqueretur, intellegere, quid diceret? Hoc positum in Phaedro a Platone probavit Epicurus sensitque in omni disputatione id fieri oportere. Aderamus nos quidem adolescentes, sed multi amplissimi viri, quorum nemo censuit plus Fadiae dandum, quam posset ad eam lege Voconia pervenire. Nec vero umquam summum bonum assequi quisquam posset, si omnia illa, quae sunt extra, quamquam expetenda, summo bono continerentur. <a href="http://loripsum.net/" target="_blank">Cur iustitia laudatur?</a> <b>Nulla erit controversia.</b> </p>

                <p>Memini vero, inquam; <b>Cur iustitia laudatur?</b> <i>Quia nec honesto quic quam honestius nec turpi turpius.</i> Quae dici eadem de ceteris virtutibus possunt, quarum omnium fundamenta vos in voluptate tamquam in aqua ponitis. <b>Immo alio genere;</b> Hos contra singulos dici est melius. Septem autem illi non suo, sed populorum suffragio omnium nominati sunt. <mark>Cur, nisi quod turpis oratio est?</mark> Quo minus animus a se ipse dissidens secumque discordans gustare partem ullam liquidae voluptatis et liberae potest. Quid, quod homines infima fortuna, nulla spe rerum gerendarum, opifices denique delectantur historia? <b>Negabat igitur ullam esse artem, quae ipsa a se proficisceretur;</b> Sed tamen omne, quod de re bona dilucide dicitur, mihi praeclare dici videtur. </p>

                <p><i>Quis hoc dicit?</i> <mark>Respondent extrema primis, media utrisque, omnia omnibus.</mark> Hoc etsi multimodis reprehendi potest, tamen accipio, quod dant. Aberat omnis dolor, qui si adesset, nec molliter ferret et tamen medicis plus quam philosophis uteretur. Quid enim ab antiquis ex eo genere, quod ad disserendum valet, praetermissum est? Qui igitur convenit ab alia voluptate dicere naturam proficisci, in alia summum bonum ponere? Nam si amitti vita beata potest, beata esse non potest. Ita similis erit ei finis boni, atque antea fuerat, neque idem tamen; <a href="http://loripsum.net/" target="_blank">Itaque hic ipse iam pridem est reiectus;</a> Si autem id non concedatur, non continuo vita beata tollitur. </p>

                <p>Omnibus enim artibus volumus attributam esse eam, quae communis appellatur prudentia, quam omnes, qui cuique artificio praesunt, debent habere. Iis igitur est difficilius satis facere, qui se Latina scripta dicunt contemnere. Iis igitur est difficilius satis facere, qui se Latina scripta dicunt contemnere. Quod autem magnum dolorem brevem, longinquum levem esse dicitis, id non intellego quale sit. <mark>Collatio igitur ista te nihil iuvat.</mark> <mark>Quare conare, quaeso.</mark> Quem Tiberina descensio festo illo die tanto gaudio affecit, quanto L. Ait enim se, si uratur, Quam hoc suave! dicturum. </p>

                <p><b>At multis se probavit.</b> Minime vero probatur huic disciplinae, de qua loquor, aut iustitiam aut amicitiam propter utilitates adscisci aut probari. Cuius quidem, quoniam Stoicus fuit, sententia condemnata mihi videtur esse inanitas ista verborum. Post enim Chrysippum eum non sane est disputatum. Num igitur dubium est, quin, si in re ipsa nihil peccatur a superioribus, verbis illi commodius utantur? Sed tu, ut dignum est tua erga me et philosophiam voluntate ab adolescentulo suscepta, fac ut Metrodori tueare liberos. Nec enim, omnes avaritias si aeque avaritias esse dixerimus, sequetur ut etiam aequas esse dicamus. Quoniamque non dubium est quin in iis, quae media dicimus, sit aliud sumendum, aliud reiciendum, quicquid ita fit aut dicitur, omne officio continetur. <a href="http://loripsum.net/" target="_blank">Sed fortuna fortis;</a> </p>

                <p>Hanc se tuus Epicurus omnino ignorare dicit quam aut qualem esse velint qui honestate summum bonum metiantur. Ergo instituto veterum, quo etiam Stoici utuntur, hinc capiamus exordium. Sic enim maiores nostri labores non fugiendos tristissimo tamen verbo aerumnas etiam in deo nominaverunt. <b>Apparet statim, quae sint officia, quae actiones.</b> <a href="http://loripsum.net/" target="_blank">Eam tum adesse, cum dolor omnis absit;</a> Iis igitur est difficilius satis facere, qui se Latina scripta dicunt contemnere. Scripta sane et multa et polita, sed nescio quo pacto auctoritatem oratio non habet. </p>

                <p>Et quod est munus, quod opus sapientiae? Graecis hoc modicum est: Leonidas, Epaminondas, tres aliqui aut quattuor; Cognitio autem haec est una nostri, ut vim corporis animique norimus sequamurque eam vitam, quae rebus iis ipsis perfruatur. Paupertas si malum est, mendicus beatus esse nemo potest, quamvis sit sapiens. <b>Nihil enim hoc differt.</b> Utrum igitur tibi non placet, inquit, virtutisne tantam esse vim, ut ad beate vivendum se ipsa contenta sit? Ut enim, inquit, gubernator aeque peccat, si palearum navem evertit et si auri, item aeque peccat, qui parentem et qui servum iniuria verberat. In eo autem voluptas omnium Latine loquentium more ponitur, cum percipitur ea, quae sensum aliquem moveat, iucunditas. <a href="http://loripsum.net/" target="_blank">Si quicquam extra virtutem habeatur in bonis.</a> <a href="http://loripsum.net/" target="_blank">Quod totum contra est.</a> </p>

                <p><a href="http://loripsum.net/" target="_blank">Pauca mutat vel plura sane;</a> Satis est tibi in te, satis in legibus, satis in mediocribus amicitiis praesidii. Qui autem de summo bono dissentit de tota philosophiae ratione dissentit. Sed tempus est, si videtur, et recta quidem ad me. Sic igitur in homine perfectio ista in eo potissimum, quod est optimum, id est in virtute, laudatur. Sed finge non solum callidum eum, qui aliquid improbe faciat, verum etiam praepotentem, ut M. Alia quaedam dicent, credo, magna antiquorum esse peccata, quae ille veri investigandi cupidus nullo modo ferre potuerit. Non enim hilaritate nec lascivia nec risu aut ioco, comite levitatis, saepe etiam tristes firmitate et constantia sunt beati. Nam et a te perfici istam disputationem volo, nec tua mihi oratio longa videri potest. Atque ut a corpore ordiar, videsne ut, si quae in membris prava aut debilitata aut inminuta sint, occultent homines? <a href="http://loripsum.net/" target="_blank">Illud non continuo, ut aeque incontentae.</a> </p>

                <p>Quae rursus dum sibi evelli ex ordine nolunt, horridiores evadunt, asperiores, duriores et oratione et moribus. An hoc usque quaque, aliter in vita? E quo efficitur, non ut nos non intellegamus quae vis sit istius verbi, sed ut ille suo more loquatur, nostrum neglegat. Et summatim quidem haec erant de corpore animoque dicenda, quibus quasi informatum est quid hominis natura postulet. Miserum hominem! Si dolor summum malum est, dici aliter non potest. <a href="http://loripsum.net/" target="_blank">Optime, inquam.</a> Quid autem est amare, e quo nomen ductum amicitiae est, nisi velle bonis aliquem affici quam maximis, etiamsi ad se ex iis nihil redundet? Idem fecisset Epicurus, si sententiam hanc, quae nunc Hieronymi est, coniunxisset cum Aristippi vetere sententia. Quodsi vultum tibi, si incessum fingeres, quo gravior viderere, non esses tui similis; Tu autem, si tibi illa probabantur, cur non propriis verbis ea tenebas? </p>

                <p>Quia, cum a Zenone, inquam, hoc magnifice tamquam ex oraculo editur: Virtus ad beate vivendum se ipsa contenta est, et Quare? Familiares nostros, credo, Sironem dicis et Philodemum, cum optimos viros, tum homines doctissimos. Sed tamen enitar et, si minus multa mihi occurrent, non fugiam ista popularia. <b>Comprehensum, quod cognitum non habet?</b> Atque ab his initiis profecti omnium virtutum et originem et progressionem persecuti sunt. <b>Non quam nostram quidem, inquit Pomponius iocans;</b> <a href="http://loripsum.net/" target="_blank">Haec para/doca illi, nos admirabilia dicamus.</a> Totum genus hoc Zeno et qui ab eo sunt aut non potuerunt aut noluerunt, certe reliquerunt. </p>

                <p>Et nemo nimium beatus est; Nonne videmus quanta perturbatio rerum omnium consequatur, quanta confusio? <i>Quis hoc dicit?</i> <mark>Diodorus, eius auditor, adiungit ad honestatem vacuitatem doloris.</mark> Nulla profecto est, quin suam vim retineat a primo ad extremum. Idem etiam dolorem saepe perpetiuntur, ne, si id non faciant, incidant in maiorem. Quae quo sunt excelsiores, eo dant clariora indicia naturae. Itaque nostrum est-quod nostrum dico, artis est-ad ea principia, quae accepimus. <i>Traditur, inquit, ab Epicuro ratio neglegendi doloris.</i> <a href="http://loripsum.net/" target="_blank">Non est ista, inquam, Piso, magna dissensio.</a> Quid ergo attinet dicere: Nihil haberem, quod reprehenderem, si finitas cupiditates haberent? Fortitudinis quaedam praecepta sunt ac paene leges, quae effeminari virum vetant in dolore. Cyrenaici quidem non recusant; <b>Ratio enim nostra consentit, pugnat oratio.</b> </p>

                <p>Fortitudinis quaedam praecepta sunt ac paene leges, quae effeminari virum vetant in dolore. Tenesne igitur, inquam, Hieronymus Rhodius quid dicat esse summum bonum, quo putet omnia referri oportere? Nemo enim est, qui aliter dixerit quin omnium naturarum simile esset id, ad quod omnia referrentur, quod est ultimum rerum appetendarum. Hoc autem tempore, etsi multa in omni parte Athenarum sunt in ipsis locis indicia summorum virorum, tamen ego illa moveor exhedra. Quodsi, ne quo incommodo afficiare, non relinques amicum, tamen, ne sine fructu alligatus sis, ut moriatur optabis. Me igitur ipsum ames oportet, non mea, si veri amici futuri sumus. Cum id fugiunt, re eadem defendunt, quae Peripatetici, verba. <i>Huius ego nunc auctoritatem sequens idem faciam.</i> Vadem te ad mortem tyranno dabis pro amico, ut Pythagoreus ille Siculo fecit tyranno? </p>

                <p><b>Dicimus aliquem hilare vivere;</b> <a href="http://loripsum.net/" target="_blank">Equidem, sed audistine modo de Carneade?</a> Crassus fuit, qui tamen solebat uti suo bono, ut hodie est noster Pompeius, cui recte facienti gratia est habenda; Quid, de quo nulla dissensio est? Magno hic ingenio, sed res se tamen sic habet, ut nimis imperiosi philosophi sit vetare meminisse. Non pugnem cum homine, cur tantum habeat in natura boni; Utrum igitur percurri omnem Epicuri disciplinam placet an de una voluptate quaeri, de qua omne certamen est? Atqui eorum nihil est eius generis, ut sit in fine atque extrerno bonorum. </p>

                <p><a href="http://loripsum.net/" target="_blank">Vitae autem degendae ratio maxime quidem illis placuit quieta.</a> In primo enim ortu inest teneritas ac mollitia quaedam, ut nec res videre optimas nec agere possint. Aliter homines, aliter philosophos loqui putas oportere? Non enim in selectione virtus ponenda erat, ut id ipsum, quod erat bonorum ultimum, aliud aliquid adquireret. Tum Piso: Atqui, Cicero, inquit, ista studia, si ad imitandos summos viros spectant, ingeniosorum sunt; <a href="http://loripsum.net/" target="_blank">Non igitur bene.</a> Tibi hoc incredibile, quod beatissimum. Sed haec ab Antiocho, familiari nostro, dicuntur multo melius et fortius, quam a Stasea dicebantur. </p>

                <p>Quos nisi redarguimus, omnis virtus, omne decus, omnis vera laus deserenda est. <mark>Cur id non ita fit?</mark> Omnium enim rerum principia parva sunt, sed suis progressionibus usa augentur nec sine causa; Ex quo intellegitur, quoniam se ipsi omnes natura diligant, tam insipientem quam sapientem sumpturum, quae secundum naturam sint, reiecturumque contraria. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet, ut et voluptates repudiandae sint et molestiae non recusandae. Itaque beatior Africanus cum patria illo modo loquens: Desine, Roma, tuos hostes reliquaque praeclare: Nam tibi moenimenta mei peperere labores. Possumusne hic scire qualis sit, nisi contulerimus inter nos, cum finem bonorum dixerimus, quid finis, quid etiam sit ipsum bonum? </p>

                <p><i>Quam ob rem tandem, inquit, non satisfacit?</i> Tum ille: Finem, inquit, interrogandi, si videtur, quod quidem ego a principio ita me malle dixeram hoc ipsum providens, dialecticas captiones. Quae diligentissime contra Aristonem dicuntur a Chryippo. Hoc dictum in una re latissime patet, ut in omnibus factis re, non teste moveamur. Primum in nostrane potestate est, quid meminerimus? Neque enim disputari sine reprehensione nec cum iracundia aut pertinacia recte disputari potest. Quid est, quod ab ea absolvi et perfici debeat? Intellegi quidem, ut propter aliam quampiam rem, verbi gratia propter voluptatem, nos amemus; <a href="http://loripsum.net/" target="_blank">Dat enim intervalla et relaxat.</a> <i>Et nemo nimium beatus est;</i> Equidem, sed audistine modo de Carneade? <b>Vide igitur ne non debeas verbis nostris uti, sententiis tuis.</b> </p>

                <p>Haec igitur Epicuri non probo, inquam. Res enim fortasse verae, certe graves, non ita tractantur, ut debent, sed aliquanto minutius. Illorum vero ista ipsa quam exilia de virtutis vi! Quam tantam volunt esse, ut beatum per se efficere possit. Nam aliquando posse recte fieri dicunt nulla expectata nec quaesita voluptate. Quid, si efficio ut fateare me non modo quid sit voluptas scire-est enim iucundus motus in sensu-, sed etiam quid eam tu velis esse? <a href="http://loripsum.net/" target="_blank">Falli igitur possumus.</a> Quibus natura iure responderit non esse verum aliunde finem beate vivendi, a se principia rei gerendae peti; Piso igitur hoc modo, vir optimus tuique, ut scis, amantissimus. </p>

                <p>Parvi enim primo ortu sic iacent, tamquam omnino sine animo sint. Nihil opus est exemplis hoc facere longius. Videmusne ut pueri ne verberibus quidem a contemplandis rebus perquirendisque deterreantur? Videmusne ut pueri ne verberibus quidem a contemplandis rebus perquirendisque deterreantur? <i>Quae cum essent dicta, discessimus.</i> Quia dolori non voluptas contraria est, sed doloris privatio. Et certamen honestum et disputatio splendida! omnis est enim de virtutis dignitate contentio. </p>

                <p>Sed quoniam et advesperascit et mihi ad villam revertendum est, nunc quidem hactenus; <a href="http://loripsum.net/" target="_blank">Utilitatis causa amicitia est quaesita.</a> <b>Sedulo, inquam, faciam.</b> Quo studio cum satiari non possint, omnium ceterarum rerum obliti níhil abiectum, nihil humile cogitant; A primo, ut opinor, animantium ortu petitur origo summi boni. <mark>Summae mihi videtur inscitiae.</mark> An me, inquis, tam amentem putas, ut apud imperitos isto modo loquar? Longum est enim ad omnia respondere, quae a te dicta sunt. </p>

                <p>Magni enim aestimabat pecuniam non modo non contra leges, sed etiam legibus partam. Id enim natura desiderat. Nam constitui virtus nullo modo potesti nisi ea, quae sunt prima naturae, ut ad summam pertinentia tenebit. Id enim ille summum bonum eu)qumi/an et saepe a)qambi/an appellat, id est animum terrore liberum. <b>Aliter enim nosmet ipsos nosse non possumus.</b> Hoc non est positum in nostra actione. Quamquam tu hanc copiosiorem etiam soles dicere. Si enim Zenoni licuit, cum rem aliquam invenisset inusitatam, inauditum quoque ei rei nomen inponere, cur non liceat Catoni? Nondum autem explanatum satis, erat, quid maxime natura vellet. Manebit ergo amicitia tam diu, quam diu sequetur utilitas, et, si utilitas amicitiam constituet, tollet eadem. Si stante, hoc natura videlicet vult, salvam esse se, quod concedimus; </p>

                <p>Ista similia non sunt, Cato, in quibus quamvis multum processeris tamen illud in eadem causa est, a quo abesse velis, donec evaseris; Ne tum quidem te respicies et cogitabis sibi quemque natum esse et suis voluptatibus? Odium autem et invidiam facile vitabis. Dicet pro me ipsa virtus nec dubitabit isti vestro beato M. Cuius quidem, quoniam Stoicus fuit, sententia condemnata mihi videtur esse inanitas ista verborum. Et quidem Arcesilas tuus, etsi fuit in disserendo pertinacior, tamen noster fuit; <mark>Quis istud, quaeso, nesciebat?</mark> Bonum patria: miserum exilium. Ego autem existimo, si honestum esse aliquid ostendero, quod sit ipsum vi sua propter seque expetendum, iacere vestra omnia. <i>Facillimum id quidem est, inquam.</i> </p>

                <p><a href="http://loripsum.net/" target="_blank">Sed ea mala virtuti magnitudine obruebantur.</a> <a href="http://loripsum.net/" target="_blank">Ut aliquid scire se gaudeant?</a> Eorum enim est haec querela, qui sibi cari sunt seseque diligunt. Quae etsi mihi nullo modo probantur, tamen Democritum laudatum a ceteris ab hoc, qui eum unum secutus esset, nollem vituperatum. Negat enim tenuissimo victu, id est contemptissimis escis et potionibus, minorem voluptatem percipi quam rebus exquisitissimis ad epulandum. Nunc ita separantur, ut disiuncta sint, quo nihil potest esse perversius. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet, ut et voluptates repudiandae sint et molestiae non recusandae. Nulla profecto est, quin suam vim retineat a primo ad extremum. </p>

                <p><a href="http://loripsum.net/" target="_blank">Tum mihi Piso: Quid ergo?</a> Is ita vivebat, ut nulla tam exquisita posset inveniri voluptas, qua non abundaret. Satis est tibi in te, satis in legibus, satis in mediocribus amicitiis praesidii. Atqui iste locus est, Piso, tibi etiam atque etiam confirmandus, inquam; Eorum enim est haec querela, qui sibi cari sunt seseque diligunt. Nec hoc ille non vidit, sed verborum magnificentia est et gloria delectatus. <a href="http://loripsum.net/" target="_blank">Cupiditates non Epicuri divisione finiebat, sed sua satietate.</a> Idemque diviserunt naturam hominis in animum et corpus. <i>Sic consequentibus vestris sublatis prima tolluntur.</i> Si enim ita est, vide ne facinus facias, cum mori suadeas. </p>

                <p>Huius, Lyco, oratione locuples, rebus ipsis ielunior. Id est enim, de quo quaerimus. <i>Aliter enim nosmet ipsos nosse non possumus.</i> An eum discere ea mavis, quae cum plane perdidiceriti nihil sciat? Nec vero intermittunt aut admirationem earum rerum, quae sunt ab antiquis repertae, aut investigationem novarum. Luxuriam non reprehendit, modo sit vacua infinita cupiditate et timore. Ex quo intellegitur officium medium quiddam esse, quod neque in bonis ponatur neque in contrariis. Tu autem inter haec tantam multitudinem hominum interiectam non vides nec laetantium nec dolentium? Itaque hic ipse iam pridem est reiectus; Primum cur ista res digna odio est, nisi quod est turpis? </p>

                <p><i>Aliter autem vobis placet.</i> <b>Nescio quo modo praetervolavit oratio.</b> <i>Tu quidem reddes;</i> <a href="http://loripsum.net/" target="_blank">Deprehensus omnem poenam contemnet.</a> Quod si ita sit, cur opera philosophiae sit danda nescio. An eum locum libenter invisit, ubi Demosthenes et Aeschines inter se decertare soliti sunt? <a href="http://loripsum.net/" target="_blank">Cum audissem Antiochum, Brute, ut solebam, cum M.</a> Cuius oratio attende, quaeso, Brute, satisne videatur Antiochi complexa esse sententiam, quam tibi, qui fratrem eius Aristum frequenter audieris, maxime probatam existimo. </p>

                <p>Obscura, inquit, quaedam esse confiteor, nec tamen ab illis ita dicuntur de industria, sed inest in rebus ipsis obscuritas. <a href="http://loripsum.net/" target="_blank">Pauca mutat vel plura sane;</a> Ex quo illud efficitur, qui bene cenent omnis libenter cenare, qui libenter, non continuo bene. <b>Urgent tamen et nihil remittunt.</b> Quo minus animus a se ipse dissidens secumque discordans gustare partem ullam liquidae voluptatis et liberae potest. Quae cum praeponunt, ut sit aliqua rerum selectio, naturam videntur sequi; Non metuet autem, sive celare poterit, sive opibus magnis quicquid fecerit optinere, certeque malet existimari bonus vir, ut non sit, quam esse, ut non putetur. Ne in odium veniam, si amicum destitero tueri. Alia quaedam dicent, credo, magna antiquorum esse peccata, quae ille veri investigandi cupidus nullo modo ferre potuerit. Se omnia, quae secundum naturam sint, b o n a appellare, quae autem contra, m a l a. </p>

                <p><b>Aliter enim explicari, quod quaeritur, non potest.</b> <a href="http://loripsum.net/" target="_blank">Quis Aristidem non mortuum diligit?</a> <mark>Efficiens dici potest.</mark> Quod quoniam in quo sit magna dissensio est, Carneadea nobis adhibenda divisio est, qua noster Antiochus libenter uti solet. Nec enim ille respirat, ante quam emersit, et catuli aeque caeci, prius quam dispexerunt, ac si ita futuri semper essent. </p>

                <p>Est, ut dicis, inquam. <i>Quis istud, quaeso, nesciebat?</i> Quae est igitur causa istarum angustiarum? Sic exclusis sententiis reliquorum cum praeterea nulla esse possit, haec antiquorum valeat necesse est. Conferam avum tuum Drusum cum C. Ergo illi intellegunt quid Epicurus dicat, ego non intellego? Nam quibus rebus efficiuntur voluptates, eae non sunt in potestate sapientis. Quaeque de virtutibus dicta sunt, quem ad modum eae semper voluptatibus inhaererent, eadem de amicitia dicenda sunt. <a href="http://loripsum.net/" target="_blank">Graece donan, Latine voluptatem vocant.</a> In omni enim animante est summum aliquid atque optimum, ut in equis, in canibus, quibus tamen et dolore vacare opus est et valere; </p>

                <p>Vives, inquit Aristo, magnifice atque praeclare, quod erit cumque visum ages, numquam angere, numquam cupies, numquam timebis. At modo dixeras nihil in istis rebus esse, quod interesset. <a href="http://loripsum.net/" target="_blank">Apparet statim, quae sint officia, quae actiones.</a> Tantum dico, magis fuisse vestrum agere Epicuri diem natalem, quam illius testamento cavere ut ageretur. Et quidem iure fortasse, sed tamen non gravissimum est testimonium multitudinis. Si quae forte-possumus. Etenim semper illud extra est, quod arte comprehenditur. Sapientem locupletat ipsa natura, cuius divitias Epicurus parabiles esse docuit. <i>Quis est tam dissimile homini.</i> Qui autem de summo bono dissentit de tota philosophiae ratione dissentit. </p>

                <p>Vitiosum est enim in dividendo partem in genere numerare. <a href="http://loripsum.net/" target="_blank">Minime vero, inquit ille, consentit.</a> Id et fieri posse et saepe esse factum et ad voluptates percipiendas maxime pertinere. Quod enim vituperabile est per se ipsum, id eo ipso vitium nominatum puto, vel etiam a vitio dictum vituperari. Etsi ea quidem, quae adhuc dixisti, quamvis ad aetatem recte isto modo dicerentur. Tum ille: Finem, inquit, interrogandi, si videtur, quod quidem ego a principio ita me malle dixeram hoc ipsum providens, dialecticas captiones. Inscite autem medicinae et gubernationis ultimum cum ultimo sapientiae comparatur. <b>Qui-vere falsone, quaerere mittimus-dicitur oculis se privasse;</b> <b>Ea possunt paria non esse.</b> </p>

                <p>Res tota, Torquate, non doctorum hominum, velle post mortem epulis celebrari memoriam sui nominis. <b>Praeclare hoc quidem.</b> Quod si ita se habeat, non possit beatam praestare vitam sapientia. Nam prius a se poterit quisque discedere quam appetitum earum rerum, quae sibi conducant, amittere. Inscite autem medicinae et gubernationis ultimum cum ultimo sapientiae comparatur. Quid loquor de nobis, qui ad laudem et ad decus nati, suscepti, instituti sumus? Vide ne ista sint Manliana vestra aut maiora etiam, si imperes quod facere non possim. Nam neque virtute retinetur ille in vita, nec iis, qui sine virtute sunt, mors est oppetenda. </p>

                <p>Itaque e contrario moderati aequabilesque habitus, affectiones ususque corporis apti esse ad naturam videntur. Sin tantum modo ad indicia veteris memoriae cognoscenda, curiosorum. Amicitiam autem adhibendam esse censent, quia sit ex eo genere, quae prosunt. <b>Certe nihil nisi quod possit ipsum propter se iure laudari.</b> Nec vero sum nescius esse utilitatem in historia, non modo voluptatem. Rem unam praeclarissimam omnium maximeque laudandam, penitus viderent, quonam gaudio complerentur, cum tantopere eius adumbrata opinione laetentur? <b>Nos paucis ad haec additis finem faciamus aliquando;</b> Commoda autem et incommoda in eo genere sunt, quae praeposita et reiecta diximus; Quos quidem tibi studiose et diligenter tractandos magnopere censeo. Quid, si non sensus modo ei sit datus, verum etiam animus hominis? Hoc etsi multimodis reprehendi potest, tamen accipio, quod dant. Nunc dicam de voluptate, nihil scilicet novi, ea tamen, quae te ipsum probaturum esse confidam. </p>

                <p>Nonne videmus quanta perturbatio rerum omnium consequatur, quanta confusio? Quid est igitur, inquit, quod requiras? Et quidem, Cato, hanc totam copiam iam Lucullo nostro notam esse oportebit; At quicum ioca seria, ut dicitur, quicum arcana, quicum occulta omnia? Aeque enim contingit omnibus fidibus, ut incontentae sint. </p>

                <p>Possumusne hic scire qualis sit, nisi contulerimus inter nos, cum finem bonorum dixerimus, quid finis, quid etiam sit ipsum bonum? Ea enim omnia, quae illi bona dicerent, praeposita esse, non bona, itemque illa, quae in corpore excellerent, stulte antiquos dixisse per se esse expetenda; <a href="http://loripsum.net/" target="_blank">Quare conare, quaeso.</a> Pisone in eo gymnasio, quod Ptolomaeum vocatur, unaque nobiscum Q. <a href="http://loripsum.net/" target="_blank">At coluit ipse amicitias.</a> Quae similitudo in genere etiam humano apparet. Roges enim Aristonem, bonane ei videantur haec: vacuitas doloris, divitiae, valitudo; At tu eadem ista dic in iudicio aut, si coronam times, dic in senatu. Illud urgueam, non intellegere eum quid sibi dicendum sit, cum dolorem summum malum esse dixerit. Familiares nostros, credo, Sironem dicis et Philodemum, cum optimos viros, tum homines doctissimos. Quae cum magnifice primo dici viderentur, considerata minus probabantur. Prioris generis est docilitas, memoria; </p>

                <p><a href="http://loripsum.net/" target="_blank">Quis istud, quaeso, nesciebat?</a> <b>Unum est sine dolore esse, alterum cum voluptate.</b> Hoc uno captus Erillus scientiam summum bonum esse defendit nec rem ullam aliam per se expetendam. </p>

                <p>Si mala non sunt, iacet omnis ratio Peripateticorum. Unum nescio, quo modo possit, si luxuriosus sit, finitas cupiditates habere. <b>Haeret in salebra.</b> Quid ad utilitatem tantae pecuniae? Non est enim vitium in oratione solum, sed etiam in moribus. <a href="http://loripsum.net/" target="_blank">Ita ne hoc quidem modo paria peccata sunt.</a> Nam si dicent ab illis has res esse tractatas, ne ipsos quidem Graecos est cur tam multos legant, quam legendi sunt. Sed audiamus ipsum: Compensabatur, inquit, tamen cum his omnibus animi laetitia, quam capiebam memoria rationum inventorumque nostrorum. </p>

                <p>Maximeque eos videre possumus res gestas audire et legere velle, qui a spe gerendi absunt confecti senectute. <a href="http://loripsum.net/" target="_blank">Quam ob rem tandem, inquit, non satisfacit?</a> Itaque sensibus rationem adiunxit et ratione effecta sensus non reliquit. Collige omnia, quae soletis: Praesidium amicorum. Quid ergo dubitamus, quin, si non dolere voluptas sit summa, non esse in voluptate dolor sit maximus? Habent enim et bene longam et satis litigiosam disputationem. Quem quidem vos, cum improbis poenam proponitis, inpetibilem facitis, cum sapientem semper boni plus habere vultis, tolerabilem. </p>

                <p>Tibi hoc incredibile, quod beatissimum. Iis igitur est difficilius satis facere, qui se Latina scripta dicunt contemnere. Itaque et manendi in vita et migrandi ratio omnis iis rebus, quas supra dixi, metienda. Idem iste, inquam, de voluptate quid sentit? <a href="http://loripsum.net/" target="_blank">Iam id ipsum absurdum, maximum malum neglegi.</a> Non dolere, inquam, istud quam vim habeat postea videro; His similes sunt omnes, qui virtuti student levantur vitiis, levantur erroribus, nisi forte censes Ti. Sed ego in hoc resisto; Quis est autem dignus nomine hominis, qui unum diem totum velit esse in genere isto voluptatis? <a href="http://loripsum.net/" target="_blank">Urgent tamen et nihil remittunt.</a> Quem quidem vos, cum improbis poenam proponitis, inpetibilem facitis, cum sapientem semper boni plus habere vultis, tolerabilem. <i>Quis Aristidem non mortuum diligit?</i> </p>

                <p><a href="http://loripsum.net/" target="_blank">Quonam, inquit, modo?</a> <i>Sed tu istuc dixti bene Latine, parum plane.</i> Poterat autem inpune; <a href="http://loripsum.net/" target="_blank">Suo enim quisque studio maxime ducitur.</a> Nec enim figura corporis nec ratio excellens ingenii humani significat ad unam hanc rem natum hominem, ut frueretur voluptatibus. Stuprata per vim Lucretia a regis filio testata civis se ipsa interemit. Quae animi affectio suum cuique tribuens atque hanc, quam dico. Sed non alienum est, quo facilius vis verbi intellegatur, rationem huius verbi faciendi Zenonis exponere. </p>

                <p>Tum ille: Finem, inquit, interrogandi, si videtur, quod quidem ego a principio ita me malle dixeram hoc ipsum providens, dialecticas captiones. Atque hoc loco similitudines eas, quibus illi uti solent, dissimillimas proferebas. Pudebit te, inquam, illius tabulae, quam Cleanthes sane commode verbis depingere solebat. <b>Summae mihi videtur inscitiae.</b> Itaque his sapiens semper vacabit. Quaesita enim virtus est, non quae relinqueret naturam, sed quae tueretur. </p>

                <p>Superiores tres erant, quae esse possent, quarum est una sola defensa, eaque vehementer. Desideraret enim valitudinem, vacuitatem doloris, appeteret etiam conservationem sui earumque rerum custodiam finemque, sibi constitueret secundum naturam vivere. <b>Iam in altera philosophiae parte.</b> Quis enim confidit semper sibi illud stabile et firmum permansurum, quod fragile et caducum sit? Parvi enim primo ortu sic iacent, tamquam omnino sine animo sint. Hos contra singulos dici est melius. <a href="http://loripsum.net/" target="_blank">Haeret in salebra.</a> Aut, Pylades cum sis, dices te esse Orestem, ut moriare pro amico? </p>

                <p>Satisne igitur videor vim verborum tenere, an sum etiam nunc vel Graece loqui vel Latine docendus? Sin autem voluptatem putat adiungendam eam, quae sit in motu-sic enim appellat hanc dulcem: in motu, illam nihil dolentis in stabilitate-, quid tendit? Illa enim, quae prosunt aut quae nocent, aut bona sunt aut mala, quae sint paria necesse est. Quis est enim, in quo sit cupiditas, quin recte cupidus dici possit? Non quaeritur autem quid naturae tuae consentaneum sit, sed quid disciplinae. <i>Id enim natura desiderat.</i> Sin autem eos non probabat, quid attinuit cum iis, quibuscum re concinebat, verbis discrepare? Et non ex maxima parte de tota iudicabis? Sin ea non neglegemus neque tamen ad finem summi boni referemus, non multum ab Erilli levitate aberrabimus. Si qua in iis corrigere voluit, deteriora fecit. </p>


            </div>
        )
    }
}

export default Index;